# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Daily Tasks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
      - run: npm i -g pnpm
      - run: pnpm install

  start:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts
          registry-url: https://registry.npmjs.org/
      - run: pnpm start
        env:
          MW_API_ENDPOINT: ${{ secrets.MW_API_ENDPOINT }}
          MW_BOT_USERNAME: ${{ secrets.MW_BOT_USERNAME }}
          MW_BOT_PASSWORD: ${{ secrets.MW_BOT_PASSWORD }}
